# Creates a list with only unique items

class ulist(list):
    def __init__(self,alist):
        self.mydict = dict()
        super().__init__([])
        for item in alist:
            if self.mydict.get(item) == None:
                self.append(item)
                self.mydict[item] = 1
            else:
                self.mydict[item] = self.mydict[item] + 1

if __name__ == '__main__':
    str1 = "In this study we used domain engineering as a method for gaining deeper formal understanding of a class of algorithms. Specifically, we analyzed 6 stemming algorithms from 4 different sub-domains of the conflation algorithms domain and developed formal domain models and generators based on these models. The application generator produces source code for not only affix removal but also successor variety, table lookup, and n-gram stemmers. The performance of the generated stemmers was compared with the stemmers developed manually in terms of stem similarity, source, and executable sizes, and development and execution times. Five of the stemmers generated by the application generator produced more than 99.9% identical stems with the manually developed stemmers. Some of the generated stemmers were as efficient as their manual equivalents and some were not."
    l1 = str1.split()
    ul1 = ulist(l1)

    print("Unique list =", ul1)
    print("Original list =", l1)